services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlsecops-api-service  # Improved container name
    image: mlsecops-api
    ports:
      - "8000:8000"
    networks:
      - mlsecops-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: mlsecops-streamlit-service  # Improved container name
    ports:
      - "8501:8501"
    networks:
      - mlsecops-network
    depends_on:
      - api

  airflow:
    image: apache/airflow:2.8.0
    container_name: mlsecops-airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./output:/opt/airflow/output
    networks:
      - mlsecops-network
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname admin --lastname admin --role Admin --password admin --email admin@example.com &&
        airflow scheduler & airflow webserver"

networks:
  mlsecops-network:
    driver: bridge
